- name: Configure Kerberos and SSL on Hortonworks (HDF/HDP) cluster
  hosts: WHOLE-CLUSTER-ANSIBLE-GROUP
  become: yes
  vars_files:
    - passwords.yml
    - variables.yml

  tasks:
#  - name: Generate CSR files
#    include: 00_generate_csr_files.yml
#
#  - name: Install kerberos
#    include: 01_kerberos.yml
#
#  - name: Prepare nodes for SSL setup
#    include: 02_general_ssl_setup.yml
#
#  - name: Install SSL on Ambari
#    include: 03_ambari_ssl_configuration.yml
#
#  - name: Install SSL on Infra Solr
#    include: 04_Infra_Solr_SSL_conf.yml
#
#  - name: Install SSL on Ambari Metrics and Grafana
#    include: 05_Ambari_Metrics_Grafana_SSL_conf.yml
#
#  - name: Install SSL on Ranger
#    include: 06_Ranger_SSL_conf.yml
#
#  - name: Install SSL on Kafka
#    include: 07_Kafka_SSL_conf.yml
#
#  - name: Install SSL on Schema Registry
#    include: 08_Schema_Registry_SSL_Conf.yml
#
#  - name: Install SSL on NiFi
#    include: 09_NiFi_SSL_conf.yml
#
#  - name: Install SSL on NiFi Registry
#    include: 10_NiFi_Registry_SSL_conf.yml

  - name: Install SSL on WebHDFS, MapReduce, TEZ and YARN
    include: 11_WebHDFS_MapReduce_Tez_YARN_SSL_conf.yml

  - name: Install SSL on HBase
    include: 12_HBase_SSL_conf.yml

  - name: Install SSL on Hive
    include: 13_Hive_SSL_conf.yml

  - name: Install SSL on Spark
    include: 14_Spark_SSL_conf.yml
